# Install common packages (e.g., htop, tmux, wget)
- name: Install common utilities
  ansible.builtin.apt:
    name:
      - htop
      - tmux
      - wget
    state: present
  when: ansible_os_family == "Debian"

# Configure firewall (e.g., allow SSH, HTTP, HTTPS)
- name: Configure UFW firewall
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  loop:
    - 22
    - 80
    - 443