# Install PostgreSQL
- name: Install PostgreSQL
  ansible.builtin.apt:
    name: postgresql
    state: present
  when: ansible_os_family == "Debian"

# Create PostgreSQL user (using vaulted password)
- name: Create PostgreSQL user
  community.postgresql.postgresql_user:
    name: "{{ db_user }}"
    password: "{{ db_password }}" 
    state: present
  become_user: postgres # Ensure the task runs as the postgres user
  
# Create PostgreSQL database
- name: Create PostgreSQL database
  community.postgresql.postgresql_db:
    name: "{{ db_name }}"
    owner: "{{ db_user }}"
    encoding: UTF-8
    lc_collate: en_US.UTF-8
    lc_ctype: en_US.UTF-8
    template: template0
    state: present
  become_user: postgres