apiVersion: v1
kind: PersistentVolume
metadata:
  name: node-persistent-volumes
  namespace: monitoring
spec:
  capacity: 
    storage: 10Gi
  accessmodes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /mnt/node-persistent-data
