global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['app:8000']

rule_files:
  - "alert_rules.yml"

scrape_configs:
  - job_name: 'python-app'
    static_configs:
      - targets: ['app:8000']  # Replace with your server IP or hostname
    relabel_configs:
      - source_labels: [__address__]
        regex: '(.*):9100'
        target_label: instance
        replacement: '${1}'
        action: replace

