apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: node-pvc
    namespace: monitoring
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 5Gi
    storageClassName: manual