service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [jaeger]

receivers:
  otlp:
    protocols:
      grpc:
        endpoint:
  # prometheus:
  #   config:
  #     scrape_configs:
  #       - job_name: 'otel-collector'
  #         static_configs:
  #           - targets: ['app:8888']

exporters:
  jaeger:
    endpoint: jaeger:14250
    tls:
      insecure: true

